### ISSUE TITLE
CentOS 8 - Failed to sync

### ISSUE THREAD

**Issue by edavrio** [sg4r/proxmox-backup-client#7]
```
HEAD is now at 2d87f2fb bump version to 1.0.6-1
patching file .cargo/config
patching file Cargo.toml
patching file src/api2/node.rs
patching file src/tools/daemon.rs
patching file src/tools.rs
    Updating crates.io index
    Updating git repository `git://git.proxmox.com/git/pathpatterns.git`
    Updating git repository `git://git.proxmox.com/git/proxmox-fuse.git`
    Updating git repository `git://git.proxmox.com/git/pxar.git`
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to select a version for the requirement `pxar = "^0.6.1"`
  candidate versions found which didn't match: 0.7.0
  location searched: Git repository git://git.proxmox.com/git/pxar.git
  required by package `proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)`
error: failed to get `pathpatterns` as a dependency of package `proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)`

Caused by:
  failed to load source for dependency `pathpatterns`

Caused by:
  Unable to update git://git.proxmox.com/git/pathpatterns.git

Caused by:
  the source git://git.proxmox.com/git/pathpatterns.git requires a lock file to be present first before it can be
  used against vendored source code

  remove the source replacement configuration, generate a lock file, and then
  restore the source replacement configuration to continue the build
error: failed to get `pathpatterns` as a dependency of package `proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)`

Caused by:
  failed to load source for dependency `pathpatterns`

Caused by:
  Unable to update git://git.proxmox.com/git/pathpatterns.git

Caused by:
  the source git://git.proxmox.com/git/pathpatterns.git requires a lock file to be present first before it can be
  used against vendored source code

  remove the source replacement configuration, generate a lock file, and then
  restore the source replacement configuration to continue the build

```

I think there are some updates done by proxmox developers which are not fully synced.

**Comment by gsamushia** [comment]
Hi is any news about this issue?

**Comment by sg4r** [comment]
hi, i have to work on another project, i'm looking next week

**Comment by sg4r** [comment]
hi, this bug is fix.
...
   Compiling zstd-safe v1.4.13+zstd.1.4.3
   Compiling zstd v0.4.28+zstd.1.4.3
   Compiling proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)
    Finished release [optimized] target(s) in 14m 37s
   Compiling proxmox-backup v1.0.6 (/root/proxmox-backup-client/proxmox-backup)
warning: unused variable: `res`
   --> src/bin/proxmox_backup_client/mount.rs:296:13
    |
296 |             res = session_fut => {
    |             ^^^ help: if this is intentional, prefix it with an underscore: `_res`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 1m 46s
[root@pbs proxmox-backup-client]# 
[root@pbs proxmox-backup-client]# ./proxmox-backup/target/release/proxmox-backup-client version
client version: 1.0.6
[root@pbs proxmox-backup-client]# ./proxmox-backup/target/release/pxar 
Error: no command specified.
Possible commands: create, extract, help, list, mount

Usage:

pxar create <archive> <source> [OPTIONS]
pxar extract <archive> [<target>] [OPTIONS]
pxar help [{<command>}] [OPTIONS]
pxar list <archive> [OPTIONS]
pxar mount <archive> <mountpoint> [OPTIONS]
